# Generated by Django 4.1.7 on 2023-03-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_app', '0003_article_context_en_article_context_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_slug_en',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_slug_uz',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_title_en',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='favorite_title_uz',
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='gender_en',
            field=models.CharField(blank=True, choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='gender_uz',
            field=models.CharField(blank=True, choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='intensity_en',
            field=models.CharField(blank=True, choices=[('Pas daraja', 'Pas daraja'), ('Vashee qiyin daraja', 'Vashee qiyin daraja'), ("O'rtancha daraja", "O'rtancha daraja"), ('Kotta daraja', 'Kotta daraja')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='intensity_uz',
            field=models.CharField(blank=True, choices=[('Pas daraja', 'Pas daraja'), ('Vashee qiyin daraja', 'Vashee qiyin daraja'), ("O'rtancha daraja", "O'rtancha daraja"), ('Kotta daraja', 'Kotta daraja')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='part_of_body_en',
            field=models.CharField(blank=True, choices=[("Qo'l", "Qo'l"), ("Ko'krak", "Ko'krak"), ('Bel', 'Bel'), ('Qorin', 'Qorin'), ('Oyoq', 'Oyoq')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='part_of_body_uz',
            field=models.CharField(blank=True, choices=[("Qo'l", "Qo'l"), ("Ko'krak", "Ko'krak"), ('Bel', 'Bel'), ('Qorin', 'Qorin'), ('Oyoq', 'Oyoq')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='type_en',
            field=models.CharField(blank=True, choices=[('Ozish', 'Ozish'), ('Kachka', 'Kachka')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='type_uz',
            field=models.CharField(blank=True, choices=[('Ozish', 'Ozish'), ('Kachka', 'Kachka')], max_length=100, null=True),
        ),
    ]
