# Generated by Django 4.1.7 on 2023-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_app', '0004_remove_favorite_favorite_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='gender_uz',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='intensity_en',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='intensity_uz',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='part_of_body_en',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='part_of_body_uz',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='fitnessprogramm',
            name='type_uz',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_slug_uz',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_type_en',
            field=models.CharField(choices=[('Programma', 'Programma'), ('Maqola', 'Maqola')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite_type_uz',
            field=models.CharField(choices=[('Programma', 'Programma'), ('Maqola', 'Maqola')], max_length=50, null=True),
        ),
    ]
